/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CariMobilImport } from './routes/cariMobil'

// Create Virtual Routes

const RegisterLazyImport = createFileRoute('/register')()
const ProfileLazyImport = createFileRoute('/profile')()
const LoginLazyImport = createFileRoute('/login')()
const LandingpageLazyImport = createFileRoute('/landingpage')()
const IndexLazyImport = createFileRoute('/')()
const DetailcarsIdLazyImport = createFileRoute('/detailcars/$id')()
const AdminTypeLazyImport = createFileRoute('/Admin/type')()
const AdminTransmissionsLazyImport = createFileRoute('/Admin/transmissions')()
const AdminModelsLazyImport = createFileRoute('/Admin/models')()
const AdminManufacturesLazyImport = createFileRoute('/Admin/manufactures')()
const AdminFuelsLazyImport = createFileRoute('/Admin/fuels')()
const AdminCarsLazyImport = createFileRoute('/Admin/cars')()
const AdminTypesRefreshLazyImport = createFileRoute('/Admin/types/refresh')()
const AdminTypesCreateLazyImport = createFileRoute('/Admin/types/create')()
const AdminTransmissionRefreshLazyImport = createFileRoute(
  '/Admin/transmission/refresh',
)()
const AdminTransmissionCreateLazyImport = createFileRoute(
  '/Admin/transmission/create',
)()
const AdminModelRefreshLazyImport = createFileRoute('/Admin/model/refresh')()
const AdminModelCreateLazyImport = createFileRoute('/Admin/model/create')()
const AdminManufactureRefreshLazyImport = createFileRoute(
  '/Admin/manufacture/refresh',
)()
const AdminManufactureCreateLazyImport = createFileRoute(
  '/Admin/manufacture/create',
)()
const AdminFuelRefreshLazyImport = createFileRoute('/Admin/fuel/refresh')()
const AdminFuelCreateLazyImport = createFileRoute('/Admin/fuel/create')()
const AdminCarRefreshLazyImport = createFileRoute('/Admin/car/refresh')()
const AdminCarCreateLazyImport = createFileRoute('/Admin/car/create')()
const AdminTypesEditIdLazyImport = createFileRoute('/Admin/types/edit/$id')()
const AdminTransmissionEditIdLazyImport = createFileRoute(
  '/Admin/transmission/edit/$id',
)()
const AdminModelEditIdLazyImport = createFileRoute('/Admin/model/edit/$id')()
const AdminManufactureEditIdLazyImport = createFileRoute(
  '/Admin/manufacture/edit/$id',
)()
const AdminFuelEditIdLazyImport = createFileRoute('/Admin/fuel/edit/$id')()
const AdminCarEditIdLazyImport = createFileRoute('/Admin/car/edit/$id')()

// Create/Update Routes

const RegisterLazyRoute = RegisterLazyImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))

const ProfileLazyRoute = ProfileLazyImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const LandingpageLazyRoute = LandingpageLazyImport.update({
  id: '/landingpage',
  path: '/landingpage',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/landingpage.lazy').then((d) => d.Route))

const CariMobilRoute = CariMobilImport.update({
  id: '/cariMobil',
  path: '/cariMobil',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const DetailcarsIdLazyRoute = DetailcarsIdLazyImport.update({
  id: '/detailcars/$id',
  path: '/detailcars/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/detailcars/$id.lazy').then((d) => d.Route),
)

const AdminTypeLazyRoute = AdminTypeLazyImport.update({
  id: '/Admin/type',
  path: '/Admin/type',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/Admin/type.lazy').then((d) => d.Route))

const AdminTransmissionsLazyRoute = AdminTransmissionsLazyImport.update({
  id: '/Admin/transmissions',
  path: '/Admin/transmissions',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/Admin/transmissions.lazy').then((d) => d.Route),
)

const AdminModelsLazyRoute = AdminModelsLazyImport.update({
  id: '/Admin/models',
  path: '/Admin/models',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/Admin/models.lazy').then((d) => d.Route))

const AdminManufacturesLazyRoute = AdminManufacturesLazyImport.update({
  id: '/Admin/manufactures',
  path: '/Admin/manufactures',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/Admin/manufactures.lazy').then((d) => d.Route),
)

const AdminFuelsLazyRoute = AdminFuelsLazyImport.update({
  id: '/Admin/fuels',
  path: '/Admin/fuels',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/Admin/fuels.lazy').then((d) => d.Route))

const AdminCarsLazyRoute = AdminCarsLazyImport.update({
  id: '/Admin/cars',
  path: '/Admin/cars',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/Admin/cars.lazy').then((d) => d.Route))

const AdminTypesRefreshLazyRoute = AdminTypesRefreshLazyImport.update({
  id: '/Admin/types/refresh',
  path: '/Admin/types/refresh',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/Admin/types/refresh.lazy').then((d) => d.Route),
)

const AdminTypesCreateLazyRoute = AdminTypesCreateLazyImport.update({
  id: '/Admin/types/create',
  path: '/Admin/types/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/Admin/types/create.lazy').then((d) => d.Route),
)

const AdminTransmissionRefreshLazyRoute =
  AdminTransmissionRefreshLazyImport.update({
    id: '/Admin/transmission/refresh',
    path: '/Admin/transmission/refresh',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/Admin/transmission/refresh.lazy').then((d) => d.Route),
  )

const AdminTransmissionCreateLazyRoute =
  AdminTransmissionCreateLazyImport.update({
    id: '/Admin/transmission/create',
    path: '/Admin/transmission/create',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/Admin/transmission/create.lazy').then((d) => d.Route),
  )

const AdminModelRefreshLazyRoute = AdminModelRefreshLazyImport.update({
  id: '/Admin/model/refresh',
  path: '/Admin/model/refresh',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/Admin/model/refresh.lazy').then((d) => d.Route),
)

const AdminModelCreateLazyRoute = AdminModelCreateLazyImport.update({
  id: '/Admin/model/create',
  path: '/Admin/model/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/Admin/model/create.lazy').then((d) => d.Route),
)

const AdminManufactureRefreshLazyRoute =
  AdminManufactureRefreshLazyImport.update({
    id: '/Admin/manufacture/refresh',
    path: '/Admin/manufacture/refresh',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/Admin/manufacture/refresh.lazy').then((d) => d.Route),
  )

const AdminManufactureCreateLazyRoute = AdminManufactureCreateLazyImport.update(
  {
    id: '/Admin/manufacture/create',
    path: '/Admin/manufacture/create',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/Admin/manufacture/create.lazy').then((d) => d.Route),
)

const AdminFuelRefreshLazyRoute = AdminFuelRefreshLazyImport.update({
  id: '/Admin/fuel/refresh',
  path: '/Admin/fuel/refresh',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/Admin/fuel/refresh.lazy').then((d) => d.Route),
)

const AdminFuelCreateLazyRoute = AdminFuelCreateLazyImport.update({
  id: '/Admin/fuel/create',
  path: '/Admin/fuel/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/Admin/fuel/create.lazy').then((d) => d.Route),
)

const AdminCarRefreshLazyRoute = AdminCarRefreshLazyImport.update({
  id: '/Admin/car/refresh',
  path: '/Admin/car/refresh',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/Admin/car/refresh.lazy').then((d) => d.Route),
)

const AdminCarCreateLazyRoute = AdminCarCreateLazyImport.update({
  id: '/Admin/car/create',
  path: '/Admin/car/create',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/Admin/car/create.lazy').then((d) => d.Route),
)

const AdminTypesEditIdLazyRoute = AdminTypesEditIdLazyImport.update({
  id: '/Admin/types/edit/$id',
  path: '/Admin/types/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/Admin/types/edit/$id.lazy').then((d) => d.Route),
)

const AdminTransmissionEditIdLazyRoute =
  AdminTransmissionEditIdLazyImport.update({
    id: '/Admin/transmission/edit/$id',
    path: '/Admin/transmission/edit/$id',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/Admin/transmission/edit/$id.lazy').then((d) => d.Route),
  )

const AdminModelEditIdLazyRoute = AdminModelEditIdLazyImport.update({
  id: '/Admin/model/edit/$id',
  path: '/Admin/model/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/Admin/model/edit/$id.lazy').then((d) => d.Route),
)

const AdminManufactureEditIdLazyRoute = AdminManufactureEditIdLazyImport.update(
  {
    id: '/Admin/manufacture/edit/$id',
    path: '/Admin/manufacture/edit/$id',
    getParentRoute: () => rootRoute,
  } as any,
).lazy(() =>
  import('./routes/Admin/manufacture/edit/$id.lazy').then((d) => d.Route),
)

const AdminFuelEditIdLazyRoute = AdminFuelEditIdLazyImport.update({
  id: '/Admin/fuel/edit/$id',
  path: '/Admin/fuel/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/Admin/fuel/edit/$id.lazy').then((d) => d.Route),
)

const AdminCarEditIdLazyRoute = AdminCarEditIdLazyImport.update({
  id: '/Admin/car/edit/$id',
  path: '/Admin/car/edit/$id',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/Admin/car/edit/$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cariMobil': {
      id: '/cariMobil'
      path: '/cariMobil'
      fullPath: '/cariMobil'
      preLoaderRoute: typeof CariMobilImport
      parentRoute: typeof rootRoute
    }
    '/landingpage': {
      id: '/landingpage'
      path: '/landingpage'
      fullPath: '/landingpage'
      preLoaderRoute: typeof LandingpageLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/cars': {
      id: '/Admin/cars'
      path: '/Admin/cars'
      fullPath: '/Admin/cars'
      preLoaderRoute: typeof AdminCarsLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/fuels': {
      id: '/Admin/fuels'
      path: '/Admin/fuels'
      fullPath: '/Admin/fuels'
      preLoaderRoute: typeof AdminFuelsLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/manufactures': {
      id: '/Admin/manufactures'
      path: '/Admin/manufactures'
      fullPath: '/Admin/manufactures'
      preLoaderRoute: typeof AdminManufacturesLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/models': {
      id: '/Admin/models'
      path: '/Admin/models'
      fullPath: '/Admin/models'
      preLoaderRoute: typeof AdminModelsLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/transmissions': {
      id: '/Admin/transmissions'
      path: '/Admin/transmissions'
      fullPath: '/Admin/transmissions'
      preLoaderRoute: typeof AdminTransmissionsLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/type': {
      id: '/Admin/type'
      path: '/Admin/type'
      fullPath: '/Admin/type'
      preLoaderRoute: typeof AdminTypeLazyImport
      parentRoute: typeof rootRoute
    }
    '/detailcars/$id': {
      id: '/detailcars/$id'
      path: '/detailcars/$id'
      fullPath: '/detailcars/$id'
      preLoaderRoute: typeof DetailcarsIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/car/create': {
      id: '/Admin/car/create'
      path: '/Admin/car/create'
      fullPath: '/Admin/car/create'
      preLoaderRoute: typeof AdminCarCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/car/refresh': {
      id: '/Admin/car/refresh'
      path: '/Admin/car/refresh'
      fullPath: '/Admin/car/refresh'
      preLoaderRoute: typeof AdminCarRefreshLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/fuel/create': {
      id: '/Admin/fuel/create'
      path: '/Admin/fuel/create'
      fullPath: '/Admin/fuel/create'
      preLoaderRoute: typeof AdminFuelCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/fuel/refresh': {
      id: '/Admin/fuel/refresh'
      path: '/Admin/fuel/refresh'
      fullPath: '/Admin/fuel/refresh'
      preLoaderRoute: typeof AdminFuelRefreshLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/manufacture/create': {
      id: '/Admin/manufacture/create'
      path: '/Admin/manufacture/create'
      fullPath: '/Admin/manufacture/create'
      preLoaderRoute: typeof AdminManufactureCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/manufacture/refresh': {
      id: '/Admin/manufacture/refresh'
      path: '/Admin/manufacture/refresh'
      fullPath: '/Admin/manufacture/refresh'
      preLoaderRoute: typeof AdminManufactureRefreshLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/model/create': {
      id: '/Admin/model/create'
      path: '/Admin/model/create'
      fullPath: '/Admin/model/create'
      preLoaderRoute: typeof AdminModelCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/model/refresh': {
      id: '/Admin/model/refresh'
      path: '/Admin/model/refresh'
      fullPath: '/Admin/model/refresh'
      preLoaderRoute: typeof AdminModelRefreshLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/transmission/create': {
      id: '/Admin/transmission/create'
      path: '/Admin/transmission/create'
      fullPath: '/Admin/transmission/create'
      preLoaderRoute: typeof AdminTransmissionCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/transmission/refresh': {
      id: '/Admin/transmission/refresh'
      path: '/Admin/transmission/refresh'
      fullPath: '/Admin/transmission/refresh'
      preLoaderRoute: typeof AdminTransmissionRefreshLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/types/create': {
      id: '/Admin/types/create'
      path: '/Admin/types/create'
      fullPath: '/Admin/types/create'
      preLoaderRoute: typeof AdminTypesCreateLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/types/refresh': {
      id: '/Admin/types/refresh'
      path: '/Admin/types/refresh'
      fullPath: '/Admin/types/refresh'
      preLoaderRoute: typeof AdminTypesRefreshLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/car/edit/$id': {
      id: '/Admin/car/edit/$id'
      path: '/Admin/car/edit/$id'
      fullPath: '/Admin/car/edit/$id'
      preLoaderRoute: typeof AdminCarEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/fuel/edit/$id': {
      id: '/Admin/fuel/edit/$id'
      path: '/Admin/fuel/edit/$id'
      fullPath: '/Admin/fuel/edit/$id'
      preLoaderRoute: typeof AdminFuelEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/manufacture/edit/$id': {
      id: '/Admin/manufacture/edit/$id'
      path: '/Admin/manufacture/edit/$id'
      fullPath: '/Admin/manufacture/edit/$id'
      preLoaderRoute: typeof AdminManufactureEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/model/edit/$id': {
      id: '/Admin/model/edit/$id'
      path: '/Admin/model/edit/$id'
      fullPath: '/Admin/model/edit/$id'
      preLoaderRoute: typeof AdminModelEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/transmission/edit/$id': {
      id: '/Admin/transmission/edit/$id'
      path: '/Admin/transmission/edit/$id'
      fullPath: '/Admin/transmission/edit/$id'
      preLoaderRoute: typeof AdminTransmissionEditIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/Admin/types/edit/$id': {
      id: '/Admin/types/edit/$id'
      path: '/Admin/types/edit/$id'
      fullPath: '/Admin/types/edit/$id'
      preLoaderRoute: typeof AdminTypesEditIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/cariMobil': typeof CariMobilRoute
  '/landingpage': typeof LandingpageLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/Admin/cars': typeof AdminCarsLazyRoute
  '/Admin/fuels': typeof AdminFuelsLazyRoute
  '/Admin/manufactures': typeof AdminManufacturesLazyRoute
  '/Admin/models': typeof AdminModelsLazyRoute
  '/Admin/transmissions': typeof AdminTransmissionsLazyRoute
  '/Admin/type': typeof AdminTypeLazyRoute
  '/detailcars/$id': typeof DetailcarsIdLazyRoute
  '/Admin/car/create': typeof AdminCarCreateLazyRoute
  '/Admin/car/refresh': typeof AdminCarRefreshLazyRoute
  '/Admin/fuel/create': typeof AdminFuelCreateLazyRoute
  '/Admin/fuel/refresh': typeof AdminFuelRefreshLazyRoute
  '/Admin/manufacture/create': typeof AdminManufactureCreateLazyRoute
  '/Admin/manufacture/refresh': typeof AdminManufactureRefreshLazyRoute
  '/Admin/model/create': typeof AdminModelCreateLazyRoute
  '/Admin/model/refresh': typeof AdminModelRefreshLazyRoute
  '/Admin/transmission/create': typeof AdminTransmissionCreateLazyRoute
  '/Admin/transmission/refresh': typeof AdminTransmissionRefreshLazyRoute
  '/Admin/types/create': typeof AdminTypesCreateLazyRoute
  '/Admin/types/refresh': typeof AdminTypesRefreshLazyRoute
  '/Admin/car/edit/$id': typeof AdminCarEditIdLazyRoute
  '/Admin/fuel/edit/$id': typeof AdminFuelEditIdLazyRoute
  '/Admin/manufacture/edit/$id': typeof AdminManufactureEditIdLazyRoute
  '/Admin/model/edit/$id': typeof AdminModelEditIdLazyRoute
  '/Admin/transmission/edit/$id': typeof AdminTransmissionEditIdLazyRoute
  '/Admin/types/edit/$id': typeof AdminTypesEditIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/cariMobil': typeof CariMobilRoute
  '/landingpage': typeof LandingpageLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/Admin/cars': typeof AdminCarsLazyRoute
  '/Admin/fuels': typeof AdminFuelsLazyRoute
  '/Admin/manufactures': typeof AdminManufacturesLazyRoute
  '/Admin/models': typeof AdminModelsLazyRoute
  '/Admin/transmissions': typeof AdminTransmissionsLazyRoute
  '/Admin/type': typeof AdminTypeLazyRoute
  '/detailcars/$id': typeof DetailcarsIdLazyRoute
  '/Admin/car/create': typeof AdminCarCreateLazyRoute
  '/Admin/car/refresh': typeof AdminCarRefreshLazyRoute
  '/Admin/fuel/create': typeof AdminFuelCreateLazyRoute
  '/Admin/fuel/refresh': typeof AdminFuelRefreshLazyRoute
  '/Admin/manufacture/create': typeof AdminManufactureCreateLazyRoute
  '/Admin/manufacture/refresh': typeof AdminManufactureRefreshLazyRoute
  '/Admin/model/create': typeof AdminModelCreateLazyRoute
  '/Admin/model/refresh': typeof AdminModelRefreshLazyRoute
  '/Admin/transmission/create': typeof AdminTransmissionCreateLazyRoute
  '/Admin/transmission/refresh': typeof AdminTransmissionRefreshLazyRoute
  '/Admin/types/create': typeof AdminTypesCreateLazyRoute
  '/Admin/types/refresh': typeof AdminTypesRefreshLazyRoute
  '/Admin/car/edit/$id': typeof AdminCarEditIdLazyRoute
  '/Admin/fuel/edit/$id': typeof AdminFuelEditIdLazyRoute
  '/Admin/manufacture/edit/$id': typeof AdminManufactureEditIdLazyRoute
  '/Admin/model/edit/$id': typeof AdminModelEditIdLazyRoute
  '/Admin/transmission/edit/$id': typeof AdminTransmissionEditIdLazyRoute
  '/Admin/types/edit/$id': typeof AdminTypesEditIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/cariMobil': typeof CariMobilRoute
  '/landingpage': typeof LandingpageLazyRoute
  '/login': typeof LoginLazyRoute
  '/profile': typeof ProfileLazyRoute
  '/register': typeof RegisterLazyRoute
  '/Admin/cars': typeof AdminCarsLazyRoute
  '/Admin/fuels': typeof AdminFuelsLazyRoute
  '/Admin/manufactures': typeof AdminManufacturesLazyRoute
  '/Admin/models': typeof AdminModelsLazyRoute
  '/Admin/transmissions': typeof AdminTransmissionsLazyRoute
  '/Admin/type': typeof AdminTypeLazyRoute
  '/detailcars/$id': typeof DetailcarsIdLazyRoute
  '/Admin/car/create': typeof AdminCarCreateLazyRoute
  '/Admin/car/refresh': typeof AdminCarRefreshLazyRoute
  '/Admin/fuel/create': typeof AdminFuelCreateLazyRoute
  '/Admin/fuel/refresh': typeof AdminFuelRefreshLazyRoute
  '/Admin/manufacture/create': typeof AdminManufactureCreateLazyRoute
  '/Admin/manufacture/refresh': typeof AdminManufactureRefreshLazyRoute
  '/Admin/model/create': typeof AdminModelCreateLazyRoute
  '/Admin/model/refresh': typeof AdminModelRefreshLazyRoute
  '/Admin/transmission/create': typeof AdminTransmissionCreateLazyRoute
  '/Admin/transmission/refresh': typeof AdminTransmissionRefreshLazyRoute
  '/Admin/types/create': typeof AdminTypesCreateLazyRoute
  '/Admin/types/refresh': typeof AdminTypesRefreshLazyRoute
  '/Admin/car/edit/$id': typeof AdminCarEditIdLazyRoute
  '/Admin/fuel/edit/$id': typeof AdminFuelEditIdLazyRoute
  '/Admin/manufacture/edit/$id': typeof AdminManufactureEditIdLazyRoute
  '/Admin/model/edit/$id': typeof AdminModelEditIdLazyRoute
  '/Admin/transmission/edit/$id': typeof AdminTransmissionEditIdLazyRoute
  '/Admin/types/edit/$id': typeof AdminTypesEditIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cariMobil'
    | '/landingpage'
    | '/login'
    | '/profile'
    | '/register'
    | '/Admin/cars'
    | '/Admin/fuels'
    | '/Admin/manufactures'
    | '/Admin/models'
    | '/Admin/transmissions'
    | '/Admin/type'
    | '/detailcars/$id'
    | '/Admin/car/create'
    | '/Admin/car/refresh'
    | '/Admin/fuel/create'
    | '/Admin/fuel/refresh'
    | '/Admin/manufacture/create'
    | '/Admin/manufacture/refresh'
    | '/Admin/model/create'
    | '/Admin/model/refresh'
    | '/Admin/transmission/create'
    | '/Admin/transmission/refresh'
    | '/Admin/types/create'
    | '/Admin/types/refresh'
    | '/Admin/car/edit/$id'
    | '/Admin/fuel/edit/$id'
    | '/Admin/manufacture/edit/$id'
    | '/Admin/model/edit/$id'
    | '/Admin/transmission/edit/$id'
    | '/Admin/types/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cariMobil'
    | '/landingpage'
    | '/login'
    | '/profile'
    | '/register'
    | '/Admin/cars'
    | '/Admin/fuels'
    | '/Admin/manufactures'
    | '/Admin/models'
    | '/Admin/transmissions'
    | '/Admin/type'
    | '/detailcars/$id'
    | '/Admin/car/create'
    | '/Admin/car/refresh'
    | '/Admin/fuel/create'
    | '/Admin/fuel/refresh'
    | '/Admin/manufacture/create'
    | '/Admin/manufacture/refresh'
    | '/Admin/model/create'
    | '/Admin/model/refresh'
    | '/Admin/transmission/create'
    | '/Admin/transmission/refresh'
    | '/Admin/types/create'
    | '/Admin/types/refresh'
    | '/Admin/car/edit/$id'
    | '/Admin/fuel/edit/$id'
    | '/Admin/manufacture/edit/$id'
    | '/Admin/model/edit/$id'
    | '/Admin/transmission/edit/$id'
    | '/Admin/types/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/cariMobil'
    | '/landingpage'
    | '/login'
    | '/profile'
    | '/register'
    | '/Admin/cars'
    | '/Admin/fuels'
    | '/Admin/manufactures'
    | '/Admin/models'
    | '/Admin/transmissions'
    | '/Admin/type'
    | '/detailcars/$id'
    | '/Admin/car/create'
    | '/Admin/car/refresh'
    | '/Admin/fuel/create'
    | '/Admin/fuel/refresh'
    | '/Admin/manufacture/create'
    | '/Admin/manufacture/refresh'
    | '/Admin/model/create'
    | '/Admin/model/refresh'
    | '/Admin/transmission/create'
    | '/Admin/transmission/refresh'
    | '/Admin/types/create'
    | '/Admin/types/refresh'
    | '/Admin/car/edit/$id'
    | '/Admin/fuel/edit/$id'
    | '/Admin/manufacture/edit/$id'
    | '/Admin/model/edit/$id'
    | '/Admin/transmission/edit/$id'
    | '/Admin/types/edit/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CariMobilRoute: typeof CariMobilRoute
  LandingpageLazyRoute: typeof LandingpageLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  ProfileLazyRoute: typeof ProfileLazyRoute
  RegisterLazyRoute: typeof RegisterLazyRoute
  AdminCarsLazyRoute: typeof AdminCarsLazyRoute
  AdminFuelsLazyRoute: typeof AdminFuelsLazyRoute
  AdminManufacturesLazyRoute: typeof AdminManufacturesLazyRoute
  AdminModelsLazyRoute: typeof AdminModelsLazyRoute
  AdminTransmissionsLazyRoute: typeof AdminTransmissionsLazyRoute
  AdminTypeLazyRoute: typeof AdminTypeLazyRoute
  DetailcarsIdLazyRoute: typeof DetailcarsIdLazyRoute
  AdminCarCreateLazyRoute: typeof AdminCarCreateLazyRoute
  AdminCarRefreshLazyRoute: typeof AdminCarRefreshLazyRoute
  AdminFuelCreateLazyRoute: typeof AdminFuelCreateLazyRoute
  AdminFuelRefreshLazyRoute: typeof AdminFuelRefreshLazyRoute
  AdminManufactureCreateLazyRoute: typeof AdminManufactureCreateLazyRoute
  AdminManufactureRefreshLazyRoute: typeof AdminManufactureRefreshLazyRoute
  AdminModelCreateLazyRoute: typeof AdminModelCreateLazyRoute
  AdminModelRefreshLazyRoute: typeof AdminModelRefreshLazyRoute
  AdminTransmissionCreateLazyRoute: typeof AdminTransmissionCreateLazyRoute
  AdminTransmissionRefreshLazyRoute: typeof AdminTransmissionRefreshLazyRoute
  AdminTypesCreateLazyRoute: typeof AdminTypesCreateLazyRoute
  AdminTypesRefreshLazyRoute: typeof AdminTypesRefreshLazyRoute
  AdminCarEditIdLazyRoute: typeof AdminCarEditIdLazyRoute
  AdminFuelEditIdLazyRoute: typeof AdminFuelEditIdLazyRoute
  AdminManufactureEditIdLazyRoute: typeof AdminManufactureEditIdLazyRoute
  AdminModelEditIdLazyRoute: typeof AdminModelEditIdLazyRoute
  AdminTransmissionEditIdLazyRoute: typeof AdminTransmissionEditIdLazyRoute
  AdminTypesEditIdLazyRoute: typeof AdminTypesEditIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CariMobilRoute: CariMobilRoute,
  LandingpageLazyRoute: LandingpageLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  ProfileLazyRoute: ProfileLazyRoute,
  RegisterLazyRoute: RegisterLazyRoute,
  AdminCarsLazyRoute: AdminCarsLazyRoute,
  AdminFuelsLazyRoute: AdminFuelsLazyRoute,
  AdminManufacturesLazyRoute: AdminManufacturesLazyRoute,
  AdminModelsLazyRoute: AdminModelsLazyRoute,
  AdminTransmissionsLazyRoute: AdminTransmissionsLazyRoute,
  AdminTypeLazyRoute: AdminTypeLazyRoute,
  DetailcarsIdLazyRoute: DetailcarsIdLazyRoute,
  AdminCarCreateLazyRoute: AdminCarCreateLazyRoute,
  AdminCarRefreshLazyRoute: AdminCarRefreshLazyRoute,
  AdminFuelCreateLazyRoute: AdminFuelCreateLazyRoute,
  AdminFuelRefreshLazyRoute: AdminFuelRefreshLazyRoute,
  AdminManufactureCreateLazyRoute: AdminManufactureCreateLazyRoute,
  AdminManufactureRefreshLazyRoute: AdminManufactureRefreshLazyRoute,
  AdminModelCreateLazyRoute: AdminModelCreateLazyRoute,
  AdminModelRefreshLazyRoute: AdminModelRefreshLazyRoute,
  AdminTransmissionCreateLazyRoute: AdminTransmissionCreateLazyRoute,
  AdminTransmissionRefreshLazyRoute: AdminTransmissionRefreshLazyRoute,
  AdminTypesCreateLazyRoute: AdminTypesCreateLazyRoute,
  AdminTypesRefreshLazyRoute: AdminTypesRefreshLazyRoute,
  AdminCarEditIdLazyRoute: AdminCarEditIdLazyRoute,
  AdminFuelEditIdLazyRoute: AdminFuelEditIdLazyRoute,
  AdminManufactureEditIdLazyRoute: AdminManufactureEditIdLazyRoute,
  AdminModelEditIdLazyRoute: AdminModelEditIdLazyRoute,
  AdminTransmissionEditIdLazyRoute: AdminTransmissionEditIdLazyRoute,
  AdminTypesEditIdLazyRoute: AdminTypesEditIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/cariMobil",
        "/landingpage",
        "/login",
        "/profile",
        "/register",
        "/Admin/cars",
        "/Admin/fuels",
        "/Admin/manufactures",
        "/Admin/models",
        "/Admin/transmissions",
        "/Admin/type",
        "/detailcars/$id",
        "/Admin/car/create",
        "/Admin/car/refresh",
        "/Admin/fuel/create",
        "/Admin/fuel/refresh",
        "/Admin/manufacture/create",
        "/Admin/manufacture/refresh",
        "/Admin/model/create",
        "/Admin/model/refresh",
        "/Admin/transmission/create",
        "/Admin/transmission/refresh",
        "/Admin/types/create",
        "/Admin/types/refresh",
        "/Admin/car/edit/$id",
        "/Admin/fuel/edit/$id",
        "/Admin/manufacture/edit/$id",
        "/Admin/model/edit/$id",
        "/Admin/transmission/edit/$id",
        "/Admin/types/edit/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/cariMobil": {
      "filePath": "cariMobil.jsx"
    },
    "/landingpage": {
      "filePath": "landingpage.lazy.jsx"
    },
    "/login": {
      "filePath": "login.lazy.jsx"
    },
    "/profile": {
      "filePath": "profile.lazy.jsx"
    },
    "/register": {
      "filePath": "register.lazy.jsx"
    },
    "/Admin/cars": {
      "filePath": "Admin/cars.lazy.jsx"
    },
    "/Admin/fuels": {
      "filePath": "Admin/fuels.lazy.jsx"
    },
    "/Admin/manufactures": {
      "filePath": "Admin/manufactures.lazy.jsx"
    },
    "/Admin/models": {
      "filePath": "Admin/models.lazy.jsx"
    },
    "/Admin/transmissions": {
      "filePath": "Admin/transmissions.lazy.jsx"
    },
    "/Admin/type": {
      "filePath": "Admin/type.lazy.jsx"
    },
    "/detailcars/$id": {
      "filePath": "detailcars/$id.lazy.jsx"
    },
    "/Admin/car/create": {
      "filePath": "Admin/car/create.lazy.jsx"
    },
    "/Admin/car/refresh": {
      "filePath": "Admin/car/refresh.lazy.jsx"
    },
    "/Admin/fuel/create": {
      "filePath": "Admin/fuel/create.lazy.jsx"
    },
    "/Admin/fuel/refresh": {
      "filePath": "Admin/fuel/refresh.lazy.jsx"
    },
    "/Admin/manufacture/create": {
      "filePath": "Admin/manufacture/create.lazy.jsx"
    },
    "/Admin/manufacture/refresh": {
      "filePath": "Admin/manufacture/refresh.lazy.jsx"
    },
    "/Admin/model/create": {
      "filePath": "Admin/model/create.lazy.jsx"
    },
    "/Admin/model/refresh": {
      "filePath": "Admin/model/refresh.lazy.jsx"
    },
    "/Admin/transmission/create": {
      "filePath": "Admin/transmission/create.lazy.jsx"
    },
    "/Admin/transmission/refresh": {
      "filePath": "Admin/transmission/refresh.lazy.jsx"
    },
    "/Admin/types/create": {
      "filePath": "Admin/types/create.lazy.jsx"
    },
    "/Admin/types/refresh": {
      "filePath": "Admin/types/refresh.lazy.jsx"
    },
    "/Admin/car/edit/$id": {
      "filePath": "Admin/car/edit/$id.lazy.jsx"
    },
    "/Admin/fuel/edit/$id": {
      "filePath": "Admin/fuel/edit/$id.lazy.jsx"
    },
    "/Admin/manufacture/edit/$id": {
      "filePath": "Admin/manufacture/edit/$id.lazy.jsx"
    },
    "/Admin/model/edit/$id": {
      "filePath": "Admin/model/edit/$id.lazy.jsx"
    },
    "/Admin/transmission/edit/$id": {
      "filePath": "Admin/transmission/edit/$id.lazy.jsx"
    },
    "/Admin/types/edit/$id": {
      "filePath": "Admin/types/edit/$id.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
